In [16]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd
df = pd.read_csv("/workspaces/data_3500_homework/TSLA.csv")

In [18]:
df["Close/Last"] = df["Close/Last"].replace("[$]", "", regex=True).astype(float)
df.head(10)

         Date  Close/Last    Volume      Open       High        Low
0  03/24/2026      383.03  60004910   $376.56    $387.48    $376.31
1  03/23/2026      380.85  74606050   $373.09    $385.33    $372.73
2  03/20/2026      367.96  78628600   $379.85    $379.89  $364.4601
3  03/19/2026      380.30  67078260   $387.27    $387.27    $378.73
4  03/18/2026      392.78  50853150   $399.00   $403.065    $392.31
5  03/17/2026      399.27  46890470   $395.69    $400.12    $393.00
6  03/16/2026      395.56  58068340   $396.22    $403.73    $394.42
7  03/13/2026      391.20  58504090  $399.165    $400.20    $389.95
8  03/12/2026      395.01  60973790  $405.175    $406.50    $394.65
9  03/11/2026      407.82  62559930   $402.28  $416.3799    $402.15

In [19]:
df = df.iloc[::-1].reset_index(drop=True)
df.head(10)

         Date  Close/Last     Volume      Open     High        Low
0  03/25/2025      288.14  150361500   $283.60  $288.20    $271.28
1  03/26/2025      272.06  156254400   $282.66  $284.90    $266.51
2  03/27/2025      273.13  162572100   $272.48  $291.85  $271.8216
3  03/28/2025      263.55  123809400  $275.575  $276.10    $260.57
4  03/31/2025      259.16  134008900   $249.31  $260.56  $243.3601
5  04/01/2025      268.46  146486900   $263.80  $277.45    $259.25
6  04/02/2025      282.76  212787800   $254.60  $284.99    $251.27
7  04/03/2025      267.28  136174300   $265.29  $276.30    $261.51
8  04/04/2025      239.43  181229400   $255.38  $261.00    $236.00
9  04/07/2025      233.29  183453800   $223.78  $252.00    $214.25

In [20]:
df["Moving/Avg"] = df["Close/Last"].shift(1).rolling(window=5).mean()
df.head(10)

         Date  Close/Last     Volume      Open     High        Low  Moving/Avg
0  03/25/2025      288.14  150361500   $283.60  $288.20    $271.28         NaN
1  03/26/2025      272.06  156254400   $282.66  $284.90    $266.51         NaN
2  03/27/2025      273.13  162572100   $272.48  $291.85  $271.8216         NaN
3  03/28/2025      263.55  123809400  $275.575  $276.10    $260.57         NaN
4  03/31/2025      259.16  134008900   $249.31  $260.56  $243.3601         NaN
5  04/01/2025      268.46  146486900   $263.80  $277.45    $259.25     271.208
6  04/02/2025      282.76  212787800   $254.60  $284.99    $251.27     267.272
7  04/03/2025      267.28  136174300   $265.29  $276.30    $261.51     269.412
8  04/04/2025      239.43  181229400   $255.38  $261.00    $236.00     268.242
9  04/07/2025      233.29  183453800   $223.78  $252.00    $214.25     263.418

In [25]:
buy = 0
first_buy = 0
total_profit = 0

for i in range(len(df)):
    current_price = df.loc[i, "Close/Last"]
    avg_price = df.loc[i, "Moving/Avg"]

    if current_price < (avg_price * .98) and buy == 0:
        buy = current_price
        print(buy)
        if first_buy == 0:
            first_buy = current_price

    if current_price > (avg_price * 1.02) and buy != 0:
        trade_profit = current_price - buy
        buy = 0
        print(trade_profit)
        total_profit += trade_profit

239.43
32.76999999999998
241.55
9.189999999999998
275.35
22.909999999999968
334.62
28.269999999999982
342.69
-16.600000000000023
316.35
32.329999999999984
323.63
-13.759999999999991
305.3
14.610000000000014
329.31
10.699999999999989
333.87
16.96999999999997
429.83
23.420000000000016
433.09
6.220000000000027
433.72
18.69999999999999
440.1
28.269999999999982
444.26
-26.480000000000018
459.64
-10.680000000000007
419.25
30.110000000000014
416.56
8.649999999999977
410.63
6.769999999999982
392.43

In [26]:
print(total_profit)

222.36999999999983